language: java

# configure the Maven environment
before_install:
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/before_install)

install: mvn install -DskipTests=true -Dinvoker.skip=true -Dmaven.javadoc.skip=true -B -V

# main task, run the verify goal
script: mvn verify

# if the build succeeds, deploy the artifact (tests are skipped)
after_success: 
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/after_success)

# if the build fails because of an integration test, print the logs
after_failure:
  - find . -type f -path '*/target/it/*/build.log' -execdir bash -c 'if ! cat build.log | grep -qFx "[INFO] BUILD SUCCESS"; then tail -250 build.log; fi' \;

before_cache:
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/before_cache)

cache:
  directories:
    - $HOME/.m2/cached-repository

# whitelist; only deploy master branch
branches:
  only:
  - master
  - /^super\/.+$/

env:
  global:
    - secure: "S/vy8yCwDewaLoe8DxjxXXx3lZcT66xVe9ZsmTfhcufg6/y6rnX25EjDnNUDBpsogtIfL4htUCLpBAixciZIbzdpenhjK0WDbO7fnfgVHZ1uhVgjJ9dG8dVabgA7F1O69yx3sNqOlDgKVWRImM/pWidu5Qyt8Rmm9sS2ejKy+ts="
    - secure: "ed4U2UwlkJI3jqNKE2NatAIxeJV331XBgTNtuSWxcTBmIunjfWCH6WBzIkEsLto1E/x9zyIb/fBzNK9vQ4GNSqmZiRrJ+eFHXvf0YZjayJzbko3Q02PAJAkmpZZRnzuSEfh/Mxo5K2QzkqBKBsYwRYg2j10RxBYtUZ3g2xcAlO0="
