language: java
services:
  - docker
before_install:
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/before_install)
script:
  - make docker &&
    make check-docker
after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      mvn deploy:deploy;
    fi
before_cache:
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/before_cache)
cache:
  directories:
    - $HOME/.m2/cached-repository
    - src/main/docker
branches:
  except:
    - /^rd-/
env:
  global:
  - secure: "BBoHwYnFXbniuy1MF44k1byHTxRhhbXNFQhd7p6HhDwm7d4ThbdTj15weASuLEfFgIp7yX7znwiqctraETsM8CiH6CPYJcMiski57NifUMSMMC6I+l/GpPd7Ci7rrkOHQP/wKZkrZMp35o9Sf5EIveTtZXaMNCK2inmmVUBm/hw="
  - secure: "gkYYo7TL4ROzE8mWK2Iw6i1+zkyTf38J/O4KJVEMCLM3bq2gwzvsPWtfiNmk+L5FcoT9qBmfAcMkI09Dutv/I/IyiAvVZLtRzQn1oSq8ZbRiyz/KwdO1LBNYJDqJYGXYM4IFnh+Sl+MVW2zhR75OW67ENUDLdSo3hotJwtVrq4E="
