version: "2.1"
services:
  pipeline:
    image: daisyorg/pipeline2
    environment:
      PIPELINE2_WS_AUTHENTICATION: "false"
      PIPELINE2_WS_LOCALFS: "false"
      PIPELINE2_WS_HOST: "pipeline"
  webui:
    image: daisyorg/webui
    environment:
      DAISY_PIPELINE2_URL: http://pipeline:8181/ws
    ports:
      - "9000:9000"
    volumes:
      - "webui-data:/opt/pipeline2-webui/data"
    depends_on:
      pipeline:
        condition: service_healthy

volumes:
  webui-data:
