install:
  - bundle install --path gems
script:
  - make
after_success:
  - source .travis/publish.sh
cache:
  directories:
    - gems
# SBS website deployed from super-project
branches:
  except:
    - sbs-website
